// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Compute number of random values >= 0.5 and < 0.5 and print results
		int num = Integer.parseInt(args[0]);
		int big = 0;
		int small = 0;
		for (int i = 0; i < num; i++) {
			double rand = Math.random();
			if (rand >= 0.5) {
				big++;
			} else {
				small++;
			}
		}
		System.out.println("Number of values >= 0.5: " + big);
		System.out.println("Number of values < 0.5: " + small);
	}
}
